# Generated by Django 3.2 on 2024-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notifications', '0006_alter_emailnotification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
