# Generated by Django 3.2.25 on 2024-11-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0018_formplugin_use_form_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('none', 'No action'), ('email_only', 'Only send email'), ('default', 'Save to site administration and send email')], default='default', max_length=15, verbose_name='Action backend'),
        ),
    ]
